### ISSUE TITLE
&view 报错 ValidationError

### ISSUE THREAD

**Issue by SerinaNya** [LittleSkinCommspt/commspt-bot#10]
```
2020-08-29 15:04:00,457][DEBUG]: Starting new HTTPS connection (1): mcskin.littleservice.cn:443
[2020-08-29 15:04:00,833][DEBUG]: https://mcskin.littleservice.cn:443 "GET /preview/hash/86c2deb7f7f06d8f01125900632589627caf413ff954cdd87efcfd4a1401777b?png HTTP/1.1" 200 47358
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 162, in Executor
    result = await run_always_await(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 10, in run_always_await
    return await any_callable
  File "main.py", line 193, in command_view
    await app.sendGroupMessage(group, MessageChain.create(_image_message))
  File "/usr/local/lib/python3.8/site-packages/graia/application/message/chain.py", line 89, in create
    return cls(__root__=elements)
  File "/usr/local/lib/python3.8/site-packages/pydantic/main.py", line 346, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for MessageChain
__root__
  value is not a valid list (type=type_error.list)
__root__
  value is not a valid tuple (type=type_error.tuple)
```

**Comment by SerinaNya** [comment]
未真正解决
